// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA75hSngQ3lrIQddSSwvglrS_fhYUOli9I',
    appId: '1:1098806920078:web:faf911906c47c0f6625adf',
    messagingSenderId: '1098806920078',
    projectId: 'majorproject-eb284',
    authDomain: 'majorproject-eb284.firebaseapp.com',
    storageBucket: 'majorproject-eb284.firebasestorage.app',
    measurementId: 'G-KZNRMPRB4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUrwWYWT9JWwcSvFy6jY3uYf23J4K9Nqo',
    appId: '1:1098806920078:android:a527cdc962b1c19f625adf',
    messagingSenderId: '1098806920078',
    projectId: 'majorproject-eb284',
    storageBucket: 'majorproject-eb284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl8R87cMkO9W2ZsWuVIk0doIE_e4p_2_8',
    appId: '1:1098806920078:ios:a910c032c59cb564625adf',
    messagingSenderId: '1098806920078',
    projectId: 'majorproject-eb284',
    storageBucket: 'majorproject-eb284.firebasestorage.app',
    iosBundleId: 'com.example.majorproject',
  );

}